apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: List Contexts

on:
  workflow_dispatch:

jobs:
  contexts:
    steps:
    - name: event_name
      uses: docker://alpine:3.20
      run: echo "${{ cloudbees.event_name }}"
    - name: event
      uses: docker://alpine:3.20
      run: echo ${{ fromJSON(cloudbees.event) }}
    - name: home
      uses: docker://alpine:3.20
      run: echo ${{ cloudbees.home }}
    - name: run_id
      uses: docker://alpine:3.20
      run: echo ${{ cloudbees.run_id }}
    - name: run_attempt
      uses: docker://alpine:3.20
      run: echo ${{ cloudbees.run_attempt }}
    - name: version
      uses: docker://alpine:3.20
      run: echo ${{ cloudbees.version }}
