apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: List Contexts

on:
  workflow_dispatch:
  push:
    branches:
      - "cb-context"

jobs:
  contexts:
    steps:
    - name: event_name
      uses: docker://alpine:3.20
      run: echo "${{ cloudbees.event_name }}"
    - name: event
      uses: docker://alpine:3.20
      run: echo "${{ toJSON(cloudbees.event) }}"
    - name: home
      uses: docker://alpine:3.20
      run: echo ${{ cloudbees.home }}
    - name: run_id
      uses: docker://alpine:3.20
      run: echo ${{ cloudbees.run_id }}
    - name: run_attempt
      uses: docker://alpine:3.20
      run: echo ${{ cloudbees.run_attempt }}
    - name: version
      uses: docker://alpine:3.20
      run: echo ${{ cloudbees.version }}
    - name: api
      uses: docker://alpine:3.20
      run: |
        echo "${{ cloudbees.api.token }}"
        echo "${{ cloudbees.api.url }}"
    - name: scm
      uses: docker://alpine:3.20
      run: |
        echo "provider: ${{ cloudbees.scm.provider }}"
        echo "provider_url: ${{ cloudbees.scm.provider_url }}"
        echo "repository: ${{ cloudbees.scm.repository }}"
        echo "sha: ${{ cloudbees.scm.sha }}"
        echo "branch: ${{ cloudbees.scm.branch }}"
        echo "ref: ${{ cloudbees.scm.ref }}"
        echo "repositoryUrl: ${{ cloudbees.scm.repositoryUrl }}"
