apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: List Contexts

on:
  workflow_dispatch:

jobs:
  contexts:
    steps:
    - name: event_name
      uses: docker://alpine:3.20
      run: |
        echo "${{ context.event_name }}