apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: starter-workflow
jobs:
  go-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: test
        uses: docker://golang:1.22-alpine3.19
        run: go test -cover ./...
      - name: build
        uses: docker://golang:1.22-alpine3.19
        run: go build -o workflow-test ./...
      - name: scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          sonar-inclusion: \*.go
          language: LANGUAGE_GO