apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: kaniko-test

on:
  push:
    branches:
    - '**'

jobs:
  build:
    steps:
    - name: checkout
      uses: cloudbees-io/checkout@v1

    - name: build
      id: build
      uses: cloudbees-io/kaniko@v1.1.5
      with:
        context: ./.cloudbees/testing
        dockerfile: Dockerfile
        destination: ttl.sh/kaniko-test:5m
    
    - name: check
      uses: docker://alpine:3.18
      run: |
        apk add -U --no-cache curl ca-certificates
        curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >/usr/local/bin/regctl
        chmod 755 /usr/local/bin/regctl

        EXPECTED=${{ steps.build.outputs.digest }}
        ACTUAL=`regctl image digest ttl.sh/kaniko-test:5m`
        if [ "$EXPECTED" != "$ACTUAL" ]; then
          echo "expected $EXPECTED, but got $ACTUAL"
          exit 1
        fi