apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: outputs-test

on:
  workflow_dispatch:

jobs:
  my-job-1:
    outputs:
      output1: ${{ steps.step1.outputs.greeting }}
      output2: ${{ steps.step2.outputs.greeting }}
    steps:
      - name: My first step
        uses: docker://alpine:3.18
        id: step1
        run: echo "hello there" > "$CLOUDBEES_OUTPUTS/greeting"
      - name: My second step
        uses: docker://alpine:3.18
        id: step2
        run: echo "from the hive" > "$CLOUDBEES_OUTPUTS/greeting"
  my-job-2:
    needs: my-job-1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        uses: docker://alpine:3.18
        run: echo "$OUTPUT1 $OUTPUT2"