apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: check-always

on:
  push:
    branches:
    - '**'

jobs:
  build:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - name: action-with-always
        uses: p-gombola/actions@always-cond
      - name: workflow-after-action
        uses: docker://alpine:3.20
        run: |
          echo "After the action step"