apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: starter-workflow
jobs:
  build:
    runs-on: 'large'
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "hello world"