apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: action-rerun

on:
  workflow_dispatch:

jobs:
  say-hello:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: print file
        uses: docker://alpine:3.20
        run: |
          cat file.txt