apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: hello-workflow

on:
  push:
    branches: 
      - '**'

jobs:
  say-hello:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: hello
        uses: docker://alpine:3.20
        run: |
          echo "hello, hello 3A"