apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: check-always

on:
  push:
    branches:
    - '**'

jobs:
  build:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - name: workflow-fail
        uses: docker://alpine:3.20
        run: |
          exit 1
      - name: action-with-always
        if: ${{always()}}
        uses: .
      - name: workflow-should-not-run
        uses: docker://alpine:3.20
        run: |
          echo "Should not be running"