apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: hello-workflow

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  say-hello:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: hello
        uses: docker://alpine:3.20
        run: |
          echo "hello, hello id-token"
      - name: goodbye
        uses: docker://alpine:3.20
        run: echo "good bye"
